### ISSUE TITLE
Error in DbContextExtensions.cs 

### ISSUE THREAD

**Issue by diverjasongray** [PacktPublishing/ASP.NET-Core-2-and-Vue.js#2]
I am in Chapter 3 and I have worked most of my bugs out, however I am receving the following error:

Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in VueApp.dll: 'Object reference not set to an instance of an object.'
   at VueApp.Data.DbContextExtensions.EnsureSeeded(VueAppContext context) in C:\Users\1801\VueApp\Data\DbContextExtensions.cs:line 12
   at VueApp.Program.Main(String[] args) in C:\Users\1801\VueApp\Program.cs:line 29

Could use some assistance troubleshooting this.
[new 6.txt](https://github.com/PacktPublishing/ASP.NET-Core-2-and-Vue.js/files/2470223/new.6.txt)

**Comment by sturatcliffe** [comment]
Apologies for the delay in response.

It look likely that ```UserManager``` is null - as it's a static class you can't inject it in the constructor, so it needs to be set in the ```Startup.cs``` file during app configuration instead.

See lines 88-90 here: https://github.com/PacktPublishing/ASP.NET-Core-2-and-Vue.js/blob/master/Startup.cs

If this doesn't solve it, pop your code in a github repo and link me to it so I can take a look for anything else that isn't quite right.

**Comment by diverjasongray** [comment]
Looks like that fixed it!

Thank You!

Jason Gray
