### ISSUE TITLE
I have Questions...

### ISSUE THREAD

**Issue by kangdongkyun** [PacktPublishing/ASP.NET-Core-2-and-Vue.js#6]
Not Working Hot Module Replacement in chaper 3 after Refactoring the frontend setup...
Do HMRs work if you follow the book?  How does it work?

**Comment by nigel-dewar** [comment]
I found the same thing and spent some time on this. I found, that as long as you run the project in debug mode, as in " pressing F5 in vscode " and NOT doing a " dotnet run" from the console , it will work.

Try that first. Hit F5 or Control F5 from vscode to run the project (which will fire up browser for you automatically ) and see if it works for you.

If not, post a github repo and I will look at it for you. I have HMR working right through to the Chapter12 branch. So it is working.

**Comment by nigel-dewar** [comment]
And take a screen grab of your browse console as well, and post here if you see any any warnings or errors

**Comment by kangdongkyun** [comment]
wow.. until now , I do "dotnet run" in vs Code... So HMR not Working..  But hit "F5",  HMR is working!! 
Thanks!!

**Comment by nigel-dewar** [comment]
No probs. Im not sure why this is the case but it took me 2 hours to figure it out. Glad its working for you, enjoy.

**Comment by sturatcliffe** [comment]
The webpack middleware which enables HMR only works when running in "Development" mode. By default, if you simple use "dotnet run" it will run in production. The reason being, once deployed into production, the webpack middleware is not needed as all the client javascript is packaged into static files.

If you look in Startup.cs, you'll see this:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
  if (env.IsDevelopment())
  {
    app.UseDeveloperExceptionPage();
    app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
    {
      HotModuleReplacement = true
    });
  }
  else
  {
    app.UseExceptionHandler("/Home/Error");
  }

  ...
}
```

Important part is **app.UseWebpackDevMiddleware(...)** which is only included if **env.IsDevelopment** is true.

**Comment by sturatcliffe** [comment]
Closing as this should now be resolved.
